### PR TITLE
Base submodules

### PR DESCRIPTION
**Pull request by Furtif**
## Use submodules

### CODE REVIEW

**Comment by PotatoMapper** [comment]
Thanks @Furtif. If you want to help generalize this. I planned on making the parsing methodology into a seperate function on a seperate script so we can use it for potter as well. I have the files somewhere just havenr been touching my github

**Comment by Furtif** [comment]
you have wuprotos into my profil git if you want i have added yours repo pyton pogo to libs readme file into pogoprotos expecting you to keep the updated py https://github.com/Furtif/POGOProtos#libraries

**Comment by PotatoMapper** [comment]
Do you use the "releases" feature at all? I'll plan on writing up a quick script to pull updated PogoProtos and WUProtos and compiling, and pushing to repos i have for convienence.

**Comment by Furtif** [comment]
no repo base is aeonlucid i think no have right for make tags

**Pull request merged**
